services:
  postgres:
    image: postgres:17
    container_name: flipkart-uploader-postgres
    environment:
      POSTGRES_DB: flipkart_uploader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - flipkart-postgres:/var/lib/postgresql/data

volumes:
  flipkart-postgres:
